// Generated by AffineScript compiler (Deno-ESM target, issue #122)
// SPDX-License-Identifier: MPL-2.0
// ---- AffineScript Deno-ESM runtime ----
const Some = (value) => ({ tag: "Some", value });
const None = { tag: "None" };
const Ok   = (value) => ({ tag: "Ok",  value });
const Err  = (error) => ({ tag: "Err", error });
const Unit = null;
const print   = (s) => { Deno.stdout.writeSync(new TextEncoder().encode(String(s))); };
const println = (s) => { console.log(String(s)); };
// ---- Deno host shims (extern fn lowering targets, issue #122) ----
// Kept tiny + inlined so emitted modules are genuinely drop-in (no extra
// package to publish or resolve). The same surface is mirrored, for
// standalone `deno test`, by packages/affine-deno/mod.js.
const __as_ensureDir = (p) => {
  try { Deno.mkdirSync(p, { recursive: true }); }
  catch (e) { if (!(e instanceof Deno.errors.AlreadyExists)) throw e; }
};
const __as_pathJoin = (a, b) => {
  if (a.length === 0) return b;
  const sep = a.endsWith("/") || a.endsWith("\\") ? "" : "/";
  return a + sep + b;
};
const __as_readDirNames = (p) => {
  const names = [];
  for (const entry of Deno.readDirSync(p)) {
    if (entry.isFile) names.push(entry.name);
  }
  return names;
};
const __as_isNotFound = (e) => (e instanceof Deno.errors.NotFound);
const __as_walkRecursive = (root) => {
  const out = [];
  const rec = (dir) => {
    for (const entry of Deno.readDirSync(dir)) {
      const full = (dir.endsWith("/") ? dir : dir + "/") + entry.name;
      if (entry.isFile) out.push(full);
      else if (entry.isDirectory) rec(full);
    }
  };
  rec(root);
  return out;
};
const __as_regexMatch = (s, pat) => new RegExp(pat).test(String(s));
const __as_wasmInstance = (bytes) =>
  new WebAssembly.Instance(new WebAssembly.Module(bytes)).exports;
const __as_wasmCall = (exports, name, args) => Number(exports[name](...(args || [])));
// ---- WasmValue (Deno.affine #455 — Tier 1 #5, Option B) ----
// Opaque tagged value crossing the AS/JS boundary as `{ kind, v }`.
// `kind` is one of "i32" | "i64" | "f32" | "f64". The `v` payload is
// `BigInt` for i64 (preserves precision beyond 2^53), `Number` otherwise.
const __as_wv_i32 = (n) => ({ kind: "i32", v: (Number(n) | 0) });
const __as_wv_i64 = (n) => ({ kind: "i64", v: BigInt(n) });
const __as_wv_f32 = (f) => ({ kind: "f32", v: Math.fround(Number(f)) });
const __as_wv_f64 = (f) => ({ kind: "f64", v: Number(f) });
const __as_wv_as_int = (v) => {
  if (v == null) return 0;
  if (typeof v.v === "bigint") {
    // i64: truncate to safe-integer Number; caller's responsibility for
    // precision-sensitive paths (use wv_kind to detect).
    return Number(v.v);
  }
  // i32 / f32 / f64: truncate toward zero per AS Int semantics.
  return (Number(v.v) | 0);
};
const __as_wv_as_float = (v) => {
  if (v == null) return 0;
  return typeof v.v === "bigint" ? Number(v.v) : Number(v.v);
};
const __as_wv_kind = (v) => (v && typeof v.kind === "string") ? v.kind : "";
const __as_wasm_export_call = (exports, name, args) => {
  // Unmarshal AS-side [WasmValue] to raw JS scalars for the wasm call.
  const rawArgs = (args || []).map((wv) => {
    if (wv == null) return 0;
    // i64 payload is BigInt; wasm i64 imports accept BigInt directly.
    return wv.v;
  });
  const result = exports[name](...rawArgs);
  // Wrap return as f64 (lossless for any numeric; callers expecting i32/i64
  // can rebuild via wv_i32(wv_as_int(result)) or inspect wv_kind).
  if (typeof result === "bigint") {
    return { kind: "i64", v: result };
  }
  return { kind: "f64", v: Number(result) };
};
// ---- motion (bindings #4): consumer-provided import ----
// Host JS environment must expose globalThis.__as_motion (the motion
// library or a compatible mock). Tests set it in the harness before
// importing the generated module; production consumers typically do
// `import * as m from "motion"; globalThis.__as_motion = m;` once at
// module-init time. The AffineScript-side externs (stdlib/Motion.affine)
// don't see this indirection — they call __as_motion* helpers directly.
const __as_motionAnimate = (target, keyframes, options) =>
  globalThis.__as_motion.animate(target, keyframes, options);
const __as_motionAwait = (controls) =>
  Promise.resolve(controls).then(() => 0);
const __as_motionCancel = (controls) => {
  if (controls && typeof controls.cancel === "function") controls.cancel();
  return 0;
};
// `animateMini` / `tween` / `spring` / `ease` — bindings #4 follow-up
// surface. Each helper resolves the host method on globalThis.__as_motion
// at call time so a mock that only stubs a subset still works for the
// rest (the smoke harness exercises every variant).
const __as_motionAnimateMini = (target, keyframes, options) =>
  globalThis.__as_motion.animateMini(target, keyframes, options);
const __as_motionTween = (target, from, to, options) =>
  globalThis.__as_motion.tween(target, from, to, options);
const __as_motionSpring = (target, keyframes, springConfig) =>
  globalThis.__as_motion.spring(target, keyframes, springConfig);
const __as_motionEase = (name) =>
  globalThis.__as_motion.ease(name);
// ---- pixi.js (bindings #1): consumer-provided import ----
// Host JS environment exposes globalThis.__as_pixi (the PIXI namespace
// from `import * as PIXI from "pixi.js"`). Tests set it in the harness
// before importing the generated module.
const __as_pixiAppInit = async (options) => {
  const app = new globalThis.__as_pixi.Application();
  await app.init(options);
  return app;
};
const __as_pixiAppCanvas = (app) => app.canvas;
const __as_pixiAppStage = (app) => app.stage;
const __as_pixiAppTicker = (app) => app.ticker;
const __as_pixiAppDestroy = (app) => { app.destroy(); return 0; };
const __as_pixiContainerNew = () => new globalThis.__as_pixi.Container();
const __as_pixiContainerAddChild = (p, c) => { p.addChild(c); return 0; };
const __as_pixiContainerRemoveChild = (p, c) => { p.removeChild(c); return 0; };
const __as_pixiContainerSetPosition = (c, x, y) => { c.x = x; c.y = y; return 0; };
const __as_pixiContainerSetScale = (c, x, y) => { c.scale.set(x, y); return 0; };
const __as_pixiContainerSetPivot = (c, x, y) => { c.pivot.set(x, y); return 0; };
const __as_pixiContainerSetRotation = (c, rad) => { c.rotation = rad; return 0; };
const __as_pixiContainerSetAlpha = (c, a) => { c.alpha = a; return 0; };
const __as_pixiContainerSetZIndex = (c, z) => { c.zIndex = z; return 0; };
const __as_pixiContainerSetSortableChildren = (c, v) => { c.sortableChildren = v; return 0; };
const __as_pixiContainerSetEventMode = (c, mode) => { c.eventMode = mode; return 0; };
const __as_pixiContainerSetCursor = (c, cursor) => { c.cursor = cursor; return 0; };
const __as_pixiContainerSetVisible = (c, v) => { c.visible = v; return 0; };
const __as_pixiContainerOn = (c, event, handler) => { c.on(event, handler); return 0; };
const __as_pixiContainerOff = (c, event, handler) => { c.off(event, handler); return 0; };
const __as_pixiContainerDestroy = (c) => { c.destroy(); return 0; };
const __as_pixiSpriteFrom = (t) => new globalThis.__as_pixi.Sprite(t);
const __as_pixiSpriteSetAnchor = (s, x, y) => { s.anchor.set(x, y); return 0; };
// Upcasts are identity — PIXI's class hierarchy makes Sprite/Graphics/
// Text actual Container subclasses, so the JS object is the same.
const __as_pixiSpriteAsContainer = (s) => s;
const __as_pixiTextureFromUrl = (url) => globalThis.__as_pixi.Texture.from(url);
const __as_pixiGraphicsNew = () => new globalThis.__as_pixi.Graphics();
const __as_pixiGraphicsRect = (g, x, y, w, h) => { g.rect(x, y, w, h); return 0; };
const __as_pixiGraphicsFill = (g, color) => { g.fill({ color }); return 0; };
const __as_pixiGraphicsClear = (g) => { g.clear(); return 0; };
const __as_pixiGraphicsAsContainer = (g) => g;
const __as_pixiTextNew = (options) => new globalThis.__as_pixi.Text(options);
const __as_pixiTextSetText = (t, content) => { t.text = content; return 0; };
const __as_pixiTextAsContainer = (t) => t;
const __as_pixiTickerAdd = (t, cb) => { t.add(cb); return 0; };
const __as_pixiTickerStart = (t) => { t.start(); return 0; };
const __as_pixiTickerStop = (t) => { t.stop(); return 0; };
// ---- @pixi/ui (bindings #3): consumer-provided import ----
// Host JS environment exposes globalThis.__as_pixi_ui (the namespace
// from `import * as PixiUI from "@pixi/ui"`). Tests set it in the
// harness before importing the generated module; production
// consumers typically do once at module-init time. The
// AffineScript-side externs (stdlib/PixiUI.affine) don't see this
// indirection — they call __as_pixiUi* helpers directly.
//
// Upcasts to Container are identity — @pixi/ui's Button /
// FancyButton / Slider / Switch are all real PIXI.Container
// subclasses, so the JS object is the same.
const __as_pixiUiButtonNew         = (options) => new globalThis.__as_pixi_ui.Button(options);
const __as_pixiUiButtonOnPress     = (b, cb)   => { b.onPress.connect(cb); return 0; };
const __as_pixiUiButtonAsContainer = (b)       => b;
const __as_pixiUiFancyButtonNew         = (options) => new globalThis.__as_pixi_ui.FancyButton(options);
const __as_pixiUiFancyButtonAsContainer = (b)       => b;
const __as_pixiUiSliderNew         = (options) => new globalThis.__as_pixi_ui.Slider(options);
const __as_pixiUiSliderOnUpdate    = (s, cb)   => { s.onUpdate.connect(cb); return 0; };
const __as_pixiUiSliderAsContainer = (s)       => s;
const __as_pixiUiSwitchNew         = (options) => new globalThis.__as_pixi_ui.Switch(options);
const __as_pixiUiSwitchOnChange    = (sw, cb)  => { sw.onChange.connect(cb); return 0; };
const __as_pixiUiSwitchAsContainer = (sw)      => sw;
// ---- @pixi/sound (bindings #2): consumer-provided import ----
// Host JS environment exposes globalThis.__as_pixi_sound (the `Sound`
// named export from `@pixi/sound`). Tests set it in the harness before
// importing the generated module; production consumers typically do
// `import { Sound } from "@pixi/sound"; globalThis.__as_pixi_sound = Sound;`
// once at module-init time. The AffineScript-side externs
// (stdlib/PixiSound.affine) don't see this indirection — they call
// __as_pixiSound* helpers directly.
const __as_pixiSoundFrom = (url) => globalThis.__as_pixi_sound.from(url);
const __as_pixiSoundPlay = (s) => { s.play(); return 0; };
const __as_pixiSoundStop = (s) => { s.stop(); return 0; };
const __as_pixiSoundPause = (s) => { s.pause(); return 0; };
const __as_pixiSoundResume = (s) => { s.resume(); return 0; };
const __as_pixiSoundSetVolume = (s, vol) => { s.volume = vol; return 0; };
const __as_pixiSoundSetLoop = (s, loop) => { s.loop = loop; return 0; };
// ---- Ipc (bindings #9): web-platform MessageChannel/MessagePort ----
// Uses standard web globals (MessageChannel, structuredClone) — no
// consumer-side init required. Available unmodified in Deno, Node 16+,
// browsers, and Web Workers.
const __as_messageChannelNew = () => new MessageChannel();
const __as_messageChannelPort1 = (ch) => ch.port1;
const __as_messageChannelPort2 = (ch) => ch.port2;
const __as_messagePortPostMessage = (p, data) => { p.postMessage(data); return 0; };
const __as_messagePortOnMessage = (p, handler) => { p.onmessage = handler; return 0; };
const __as_messagePortStart = (p) => { p.start(); return 0; };
const __as_messagePortClose = (p) => { p.close(); return 0; };
const __as_targetPostMessage = (t, msg) => { t.postMessage(msg); return 0; };
const __as_structuredCloneValue = (v) => structuredClone(v);
// ---- Canvas (bindings #8): HTML5 Canvas 2D rendering context ----
// `canvas` arg is the consumer-supplied HTMLCanvasElement; helpers
// dispatch directly to the standard CanvasRenderingContext2D
// methods. Available unmodified in browsers, jsdom-under-Deno,
// idaptik's WebView host, and any DOM emulator.
const __as_canvasGetContext2D = (canvas) => canvas.getContext("2d");
const __as_canvasFillStyle = (ctx, color) => { ctx.fillStyle = color; return 0; };
const __as_canvasStrokeStyle = (ctx, color) => { ctx.strokeStyle = color; return 0; };
const __as_canvasLineWidth = (ctx, w) => { ctx.lineWidth = w; return 0; };
const __as_canvasGlobalAlpha = (ctx, a) => { ctx.globalAlpha = a; return 0; };
const __as_canvasFillRect = (ctx, x, y, w, h) => { ctx.fillRect(x, y, w, h); return 0; };
const __as_canvasStrokeRect = (ctx, x, y, w, h) => { ctx.strokeRect(x, y, w, h); return 0; };
const __as_canvasClearRect = (ctx, x, y, w, h) => { ctx.clearRect(x, y, w, h); return 0; };
const __as_canvasBeginPath = (ctx) => { ctx.beginPath(); return 0; };
const __as_canvasClosePath = (ctx) => { ctx.closePath(); return 0; };
const __as_canvasMoveTo = (ctx, x, y) => { ctx.moveTo(x, y); return 0; };
const __as_canvasLineTo = (ctx, x, y) => { ctx.lineTo(x, y); return 0; };
const __as_canvasArc = (ctx, x, y, r, s, e) => { ctx.arc(x, y, r, s, e); return 0; };
const __as_canvasFill = (ctx) => { ctx.fill(); return 0; };
const __as_canvasStroke = (ctx) => { ctx.stroke(); return 0; };
const __as_canvasSave = (ctx) => { ctx.save(); return 0; };
const __as_canvasRestore = (ctx) => { ctx.restore(); return 0; };
const __as_canvasTranslate = (ctx, x, y) => { ctx.translate(x, y); return 0; };
const __as_canvasRotate = (ctx, rad) => { ctx.rotate(rad); return 0; };
const __as_canvasScale = (ctx, x, y) => { ctx.scale(x, y); return 0; };
const __as_canvasFont = (ctx, font) => { ctx.font = font; return 0; };
const __as_canvasTextAlign = (ctx, align) => { ctx.textAlign = align; return 0; };
const __as_canvasTextBaseline = (ctx, baseline) => { ctx.textBaseline = baseline; return 0; };
const __as_canvasFillText = (ctx, text, x, y) => { ctx.fillText(text, x, y); return 0; };
const __as_canvasStrokeText = (ctx, text, x, y) => { ctx.strokeText(text, x, y); return 0; };
const __as_canvasMeasureText = (ctx, text) => ctx.measureText(text);
const __as_canvasDrawImage = (ctx, img, x, y) => { ctx.drawImage(img, x, y); return 0; };
const __as_canvasDrawImageScaled = (ctx, img, x, y, w, h) => { ctx.drawImage(img, x, y, w, h); return 0; };
// `++` is overloaded (string concat / array concat); `a + b` would
// stringify arrays. Dispatch on shape so stdlib/string.affine's
// `result ++ [x]` and `a ++ b` are both correct.
const __as_concat = (a, b) => Array.isArray(a) ? a.concat(b) : (a + b);
// Honest host/runtime primitives underpinning the AffineScript-level
// stdlib/string.affine (its is_empty/starts_with/ends_with/split/join/
// replace/... are real AffineScript on top of these).
const __as_strSub = (s, start, n) => String(s).slice(start, start + n);
const __as_strGet = (s, i) => String(s)[i];
const __as_strFind = (s, n) => String(s).indexOf(n);
const __as_charToInt = (c) => String(c).codePointAt(0);
const __as_intToChar = (n) => String.fromCodePoint(n);
const __as_strCharCodeAt = (s, i) => (i >= 0 && i < s.length ? s.charCodeAt(i) : -1);
const __as_strFromCharCode = (n) => String.fromCharCode(n & 0xff);
const __as_parseInt = (s) => {
  const n = parseInt(String(s), 10);
  return Number.isNaN(n) ? None : Some(n);
};
const __as_parseFloat = (s) => {
  const n = parseFloat(String(s));
  return Number.isNaN(n) ? None : Some(n);
};
const __as_show = (v) => (typeof v === "string" ? v : JSON.stringify(v));
// ---- Http (issue #160): portable fetch round-trip ----
// `headers` crosses the boundary as an AffineScript [(String, String)]
// assoc list == JS array of [name, value] pairs. `body` is an
// AffineScript Option<String> == { tag: "Some", value } | { tag: "None" }.
// The result is the `Response` record shape { status, headers, body }.
const __as_httpHeadersToObject = (pairs) => {
  const o = {};
  for (const kv of (pairs || [])) o[kv[0]] = kv[1];
  return o;
};
const __as_httpHeadersFromResponse = (res) => {
  const out = [];
  res.headers.forEach((value, key) => out.push([key, value]));
  return out;
};
// ---- hpm-json-rsr Zig FFI shims (stdlib/json.affine v0.3) ----
// `HpmJsonValue` is opaque to AffineScript; on Deno-ESM it's just the
// underlying JS value from JSON.parse. The shims mirror the sentinel
// conventions of the Zig exports so the AffineScript-side wrappers
// (`to_json`, `parse`) behave identically across backends.
const __as_hpmJsonParse = (s) => {
  try { return Some(JSON.parse(String(s))); } catch (_e) { return None; }
};
const __as_hpmJsonFree = (_v) => 0;
const __as_hpmJsonType = (v) => {
  if (v === null || v === undefined) return 0;
  if (typeof v === "boolean") return 1;
  if (typeof v === "number")  return Number.isInteger(v) ? 2 : 3;
  if (typeof v === "string")  return 4;
  if (Array.isArray(v))       return 5;
  if (typeof v === "object")  return 6;
  return -1;
};
const __as_hpmJsonBool = (v) => (typeof v === "boolean" ? (v ? 1 : 0) : -1);
const __as_hpmJsonInt = (v) =>
  (typeof v === "number" ? Math.trunc(v) : Number.MIN_SAFE_INTEGER);
const __as_hpmJsonFloat = (v) => (typeof v === "number" ? v : NaN);
const __as_hpmJsonString = (v) => (typeof v === "string" ? v : "");
const __as_hpmJsonObjectGet = (v, k) => {
  if (v === null || typeof v !== "object" || Array.isArray(v)) return None;
  return Object.prototype.hasOwnProperty.call(v, String(k))
    ? Some(v[String(k)]) : None;
};
const __as_hpmJsonArrayLen = (v) => (Array.isArray(v) ? v.length : 0);
const __as_hpmJsonArrayGet = (v, i) => {
  if (!Array.isArray(v)) return None;
  const idx = Number(i);
  return (idx >= 0 && idx < v.length) ? Some(v[idx]) : None;
};
const __as_hpmJsonEscapeString = (s) => {
  let out = "";
  const src = String(s);
  for (let i = 0; i < src.length; i++) {
    const c = src.charCodeAt(i);
    if (c === 0x22) out += "\\\"";
    else if (c === 0x5c) out += "\\\\";
    else if (c === 0x0a) out += "\\n";
    else if (c === 0x0d) out += "\\r";
    else if (c === 0x09) out += "\\t";
    else if (c === 0x08) out += "\\b";
    else if (c === 0x0c) out += "\\f";
    else if (c < 0x20) out += "\\u00" + c.toString(16).padStart(2, "0");
    else out += src[i];
  }
  return out;
};
const __as_httpFetch = async (url, method, headers, bodyOpt) => {
  const init = { method, headers: __as_httpHeadersToObject(headers) };
  if (bodyOpt && bodyOpt.tag === "Some") init.body = bodyOpt.value;
  // `globalThis.fetch` explicitly: the stdlib `Http.fetch` compiles to a
  // module-level `function fetch`, which would otherwise shadow the host.
  const res = await globalThis.fetch(url, init);
  const text = await res.text();
  return {
    status: res.status,
    headers: __as_httpHeadersFromResponse(res),
    body: text,
  };
};
// ---- end runtime ----

// type Node
// type Link
// type GraphData
export function create_node(id, label, node_type, prompt_score) {
  if ((((id).length) === 0)) { return None;  }
  if ((((label).length) === 0)) { return None;  }
  if ((prompt_score < 0.0)) { return None;  }
  if ((prompt_score > 100.0)) { return None;  }
  return Some(({ id: id, label: label, node_type: node_type, prompt_score: prompt_score }));
}

export function create_link(source, target, relationship) {
  if ((((source).length) === 0)) { return None;  }
  if ((((target).length) === 0)) { return None;  }
  if ((((relationship).length) === 0)) { return None;  }
  return Some(({ source: source, target: target, relationship: relationship }));
}

export function create_graph_data(nodes, links) {
  return ({ nodes: nodes, links: links });
}

export function empty_graph() {
  return ({ nodes: [], links: [] });
}

function fail_msg(msg) {
  const _r = (console.error(__as_concat("  FAIL: ", msg)), 0);
  return false;
}

function check_eq_str(actual, expected, label) {
  return ((actual === expected) ? (() => { return true; })() : (() => { return fail_msg(__as_concat(__as_concat(__as_concat(__as_concat(__as_concat(label, " \u2014 got '"), actual), "', expected '"), expected), "'")); })());
}

function check_eq_int(actual, expected, label) {
  return ((actual === expected) ? (() => { return true; })() : (() => { return fail_msg(__as_concat(__as_concat(__as_concat(__as_concat(label, " \u2014 got "), String(actual)), ", expected "), String(expected))); })());
}

function check_eq_float(actual, expected, label) {
  return ((actual === expected) ? (() => { return true; })() : (() => { return fail_msg(__as_concat(__as_concat(__as_concat(__as_concat(label, " \u2014 got "), String(actual)), ", expected "), String(expected))); })());
}

function check_true(condition, label) {
  return (condition ? (() => { return true; })() : (() => { return fail_msg(label); })());
}

function check_none_node(opt, label) {
  return ((__scrut) => { if (__scrut.tag === "None") { return true; } if (__scrut.tag === "Some") { return fail_msg(__as_concat(label, " \u2014 expected None, got Some")); } throw new Error("non-exhaustive match"); })(opt);
}

function check_none_link(opt, label) {
  return ((__scrut) => { if (__scrut.tag === "None") { return true; } if (__scrut.tag === "Some") { return fail_msg(__as_concat(label, " \u2014 expected None, got Some")); } throw new Error("non-exhaustive match"); })(opt);
}

function unwrap_node(opt) {
  return ((__scrut) => { if (__scrut.tag === "Some") { const n = __scrut.value;  return n; } if (__scrut.tag === "None") { return ({ id: "INVALID", label: "INVALID", node_type: "INVALID", prompt_score: 0.0 }); } throw new Error("non-exhaustive match"); })(opt);
}

function unwrap_link(opt) {
  return ((__scrut) => { if (__scrut.tag === "Some") { const l = __scrut.value;  return l; } if (__scrut.tag === "None") { return ({ source: "INVALID", target: "INVALID", relationship: "INVALID" }); } throw new Error("non-exhaustive match"); })(opt);
}

export function test_node_create_claim() {
  const n = unwrap_node(create_node("claim_1", "Climate change is occurring", "claim", 85.5));
  if ((!check_eq_str(n.id, "claim_1", "claim node id"))) { return false;  }
  if ((!check_eq_str(n.label, "Climate change is occurring", "claim node label"))) { return false;  }
  if ((!check_eq_str(n.node_type, "claim", "claim node type"))) { return false;  }
  return check_eq_float(n.prompt_score, 85.5, "claim node prompt_score");
}

export function test_node_create_evidence() {
  const n = unwrap_node(create_node("evidence_1", "IPCC AR6 Report", "evidence", 92.0));
  if ((!check_eq_str(n.id, "evidence_1", "evidence node id"))) { return false;  }
  if ((!check_eq_str(n.label, "IPCC AR6 Report", "evidence node label"))) { return false;  }
  if ((!check_eq_str(n.node_type, "evidence", "evidence node type"))) { return false;  }
  return check_eq_float(n.prompt_score, 92.0, "evidence node prompt_score");
}

export function test_node_custom_type() {
  const n = unwrap_node(create_node("node_1", "Label", "custom-type", 50.0));
  return check_eq_str(n.node_type, "custom-type", "custom node_type");
}

export function test_node_reject_empty_id() {
  return check_none_node(create_node("", "Label", "claim", 50.0), "empty id rejected");
}

export function test_node_reject_empty_label() {
  return check_none_node(create_node("id_1", "", "claim", 50.0), "empty label rejected");
}

export function test_node_reject_negative_score() {
  return check_none_node(create_node("id_1", "Label", "claim", (0.0 - 1.0)), "negative prompt_score rejected");
}

export function test_node_reject_score_over_100() {
  return check_none_node(create_node("id_1", "Label", "claim", 101.0), "prompt_score > 100 rejected");
}

export function test_node_boundary_score_0() {
  const n = unwrap_node(create_node("id_1", "Label", "claim", 0.0));
  return check_eq_float(n.prompt_score, 0.0, "boundary prompt_score 0");
}

export function test_node_boundary_score_100() {
  const n = unwrap_node(create_node("id_2", "Label", "claim", 100.0));
  return check_eq_float(n.prompt_score, 100.0, "boundary prompt_score 100");
}

export function test_link_supports() {
  const l = unwrap_link(create_link("evidence_1", "claim_1", "supports"));
  if ((!check_eq_str(l.source, "evidence_1", "supports link source"))) { return false;  }
  if ((!check_eq_str(l.target, "claim_1", "supports link target"))) { return false;  }
  return check_eq_str(l.relationship, "supports", "supports link relationship");
}

export function test_link_contradicts() {
  const l = unwrap_link(create_link("evidence_2", "claim_1", "contradicts"));
  if ((!check_eq_str(l.source, "evidence_2", "contradicts link source"))) { return false;  }
  if ((!check_eq_str(l.target, "claim_1", "contradicts link target"))) { return false;  }
  return check_eq_str(l.relationship, "contradicts", "contradicts link relationship");
}

export function test_link_contextualizes() {
  const l = unwrap_link(create_link("evidence_3", "claim_1", "contextualizes"));
  if ((!check_eq_str(l.source, "evidence_3", "contextualizes link source"))) { return false;  }
  if ((!check_eq_str(l.target, "claim_1", "contextualizes link target"))) { return false;  }
  return check_eq_str(l.relationship, "contextualizes", "contextualizes link relationship");
}

export function test_link_custom_relationship() {
  const l = unwrap_link(create_link("node_1", "node_2", "mentions"));
  return check_eq_str(l.relationship, "mentions", "custom relationship");
}

export function test_link_reject_empty_source() {
  return check_none_link(create_link("", "target", "supports"), "empty source rejected");
}

export function test_link_reject_empty_target() {
  return check_none_link(create_link("source", "", "supports"), "empty target rejected");
}

export function test_link_reject_empty_relationship() {
  return check_none_link(create_link("source", "target", ""), "empty relationship rejected");
}

export function test_graph_empty() {
  const g = empty_graph();
  if ((!check_eq_int(((g.nodes).length), 0, "empty graph nodes length"))) { return false;  }
  return check_eq_int(((g.links).length), 0, "empty graph links length");
}

export function test_graph_with_nodes() {
  const n1 = unwrap_node(create_node("claim_1", "Test claim", "claim", 75.0));
  const n2 = unwrap_node(create_node("evidence_1", "Test evidence", "evidence", 80.0));
  const g = create_graph_data([n1, n2], []);
  if ((!check_eq_int(((g.nodes).length), 2, "graph node count"))) { return false;  }
  if ((!check_eq_str(g.nodes[0].id, "claim_1", "first node id"))) { return false;  }
  return check_eq_str(g.nodes[1].id, "evidence_1", "second node id");
}

export function test_graph_with_links() {
  const n1 = unwrap_node(create_node("claim_1", "Test claim", "claim", 75.0));
  const n2 = unwrap_node(create_node("evidence_1", "Test evidence", "evidence", 80.0));
  const l1 = unwrap_link(create_link("evidence_1", "claim_1", "supports"));
  const g = create_graph_data([n1, n2], [l1]);
  if ((!check_eq_int(((g.links).length), 1, "graph link count"))) { return false;  }
  return check_eq_str(g.links[0].source, "evidence_1", "link source");
}

export function test_graph_complex() {
  const n1 = unwrap_node(create_node("claim_1", "Main claim", "claim", 85.0));
  const n2 = unwrap_node(create_node("claim_2", "Sub-claim", "claim", 70.0));
  const n3 = unwrap_node(create_node("evidence_1", "First evidence", "evidence", 90.0));
  const n4 = unwrap_node(create_node("evidence_2", "Second evidence", "evidence", 75.0));
  const l1 = unwrap_link(create_link("evidence_1", "claim_1", "supports"));
  const l2 = unwrap_link(create_link("evidence_2", "claim_1", "supports"));
  const l3 = unwrap_link(create_link("claim_1", "claim_2", "contextualizes"));
  const g = create_graph_data([n1, n2, n3, n4], [l1, l2, l3]);
  if ((!check_eq_int(((g.nodes).length), 4, "complex graph node count"))) { return false;  }
  return check_eq_int(((g.links).length), 3, "complex graph link count");
}

export function test_null_handling_via_empty_id() {
  return check_none_node(create_node("", "Label", "claim", 50.0), "AS empty-id stand-in for null id");
}

export function test_null_handling_via_empty_label() {
  return check_none_node(create_node("id_1", "", "claim", 50.0), "AS empty-label stand-in for undefined label");
}

export function test_null_handling_empty_arrays() {
  const g = create_graph_data([], []);
  if ((!check_eq_int(((g.nodes).length), 0, "empty arrays graph nodes length"))) { return false;  }
  return check_eq_int(((g.links).length), 0, "empty arrays graph links length");
}

export function test_access_all_node_fields() {
  const n = unwrap_node(create_node("test_1", "Test Node", "custom", 42.5));
  if ((!check_eq_str(n.id, "test_1", "node.id access"))) { return false;  }
  if ((!check_eq_str(n.label, "Test Node", "node.label access"))) { return false;  }
  if ((!check_eq_str(n.node_type, "custom", "node.node_type access"))) { return false;  }
  return check_eq_float(n.prompt_score, 42.5, "node.prompt_score access");
}

export function test_access_all_link_fields() {
  const l = unwrap_link(create_link("source_1", "target_1", "test-rel"));
  if ((!check_eq_str(l.source, "source_1", "link.source access"))) { return false;  }
  if ((!check_eq_str(l.target, "target_1", "link.target access"))) { return false;  }
  return check_eq_str(l.relationship, "test-rel", "link.relationship access");
}

function run_one(name, ok) {
  if (ok) { println(__as_concat("  ok ", name)); return 0;  }
  println(__as_concat("  FAIL ", name));
  return 1;
}

export function main() {
  let failed = 0;
  failed = (failed + run_one("node: create claim node", test_node_create_claim()));
  failed = (failed + run_one("node: create evidence node", test_node_create_evidence()));
  failed = (failed + run_one("node: custom type", test_node_custom_type()));
  failed = (failed + run_one("node: reject empty id", test_node_reject_empty_id()));
  failed = (failed + run_one("node: reject empty label", test_node_reject_empty_label()));
  failed = (failed + run_one("node: reject negative prompt_score", test_node_reject_negative_score()));
  failed = (failed + run_one("node: reject prompt_score > 100", test_node_reject_score_over_100()));
  failed = (failed + run_one("node: boundary prompt_score 0", test_node_boundary_score_0()));
  failed = (failed + run_one("node: boundary prompt_score 100", test_node_boundary_score_100()));
  failed = (failed + run_one("link: supports", test_link_supports()));
  failed = (failed + run_one("link: contradicts", test_link_contradicts()));
  failed = (failed + run_one("link: contextualizes", test_link_contextualizes()));
  failed = (failed + run_one("link: custom relationship", test_link_custom_relationship()));
  failed = (failed + run_one("link: reject empty source", test_link_reject_empty_source()));
  failed = (failed + run_one("link: reject empty target", test_link_reject_empty_target()));
  failed = (failed + run_one("link: reject empty relationship", test_link_reject_empty_relationship()));
  failed = (failed + run_one("graph: empty", test_graph_empty()));
  failed = (failed + run_one("graph: with nodes", test_graph_with_nodes()));
  failed = (failed + run_one("graph: with links", test_graph_with_links()));
  failed = (failed + run_one("graph: complex", test_graph_complex()));
  failed = (failed + run_one("null: empty id rejected", test_null_handling_via_empty_id()));
  failed = (failed + run_one("null: empty label rejected", test_null_handling_via_empty_label()));
  failed = (failed + run_one("null: empty arrays graph", test_null_handling_empty_arrays()));
  failed = (failed + run_one("access: all node fields", test_access_all_node_fields()));
  failed = (failed + run_one("access: all link fields", test_access_all_link_fields()));
  if ((failed > 0)) { println(""); println(__as_concat(__as_concat("FAILED: ", String(failed)), " test(s)")); return 1;  }
  println("");
  println("OK: all tests passed (25/25)");
  return 0;
}

await main();
